#!/bin/bash

TS_FILE="/var/lib/last-timestamp.txt"
TZ="Asia/Shanghai"

function showTime() {
	date -d @"$1" "+%Y-%m-%d %H:%M:%S"
}

LAST_TS="1729698548"
if [ -f "$TS_FILE" ]; then
    LAST_TS=$(cat "$TS_FILE")
fi

CURRENT_TS=$(date +%s)

if [ "$LAST_TS" -gt "$CURRENT_TS" ]; then
	date -s @"$LAST_TS"
	echo "last time: $(showTime "$LAST_TS"), current time: $(showTime "$CURRENT_TS"), changed to last time"
	exit
fi

if [ "$LAST_TS" -lt "$CURRENT_TS" ]; then
	TS=$(date +%s | sudo tee "$TS_FILE")
	echo "save time $(showTime "$TS")"
fi
