default:
	if [ ! -f /usr/local/bin/qtun-client ]; then \
		./qtun.sh; \
	fi
	if [ ! -f /usr/local/bin/v2ray-plugin ]; then \
		./v2ray.sh; \
	fi
	if [ ! -f /usr/local/bin/ssmanager ]; then \
		./run.sh; \
	fi
